run_minscanf: e4_minscanf.c
	gcc e4_minscanf.c -o minscanf

run_minprintf: e3_minprintf.c
	gcc e3_minprintf.c -o minprintf

run_convert_case_upper: e1_convert_case.c
	gcc e1_convert_case.c -o upper

run_convert_case_lower: e1_convert_case.c
	gcc e1_convert_case.c -o lower

.PHONY: clean
clean:
	rm -f lower
	rm -f upper
	rm -f minprintf
	rm -f minscanf

