run_invert: e7_invert.c
	gcc e7_invert.c -o invert

run_setbits: e6_setbits.c
	gcc e6_setbits.c -o setbits

run_any: e5_any.c
	gcc e5_any.c -o any

run_squeeze: e4_squeeze.c
	gcc e4_squeeze.c -o squeeze

run_htoi: e3_htoi.c
	gcc e3_htoi.c -o htoi

run_ops: e2_ops.c
	gcc e2_ops.c -o ops

run_cpu_limits: e1_cpu_limits.c
	gcc e1_cpu_limits.c -o cpu_limits

.PHONY: clean
clean:
	rm -f cpu_limits
	rm -f ops
	rm -f htoi
	rm -f squeeze
	rm -f any
	rm -f setbits
	rm -f invert

