run_macro_swap: e14_macro_swap.c
	gcc e14_macro_swap.c -o macro_swap

run_rec_reverse: e13_rec_reverse.c
	gcc e13_rec_reverse.c -o reverse

run_rec_itoa: e12_rec_itoa.c
	gcc e12_rec_itoa.c -o itoa

run_rev_polish: rev_polish.c
	gcc rev_polish.c -o rev_polish

run_atof: e2_atof.c
	gcc e2_atof.c -o atof

run_match: e1_match.c
	gcc e1_match.c -o match

.PHONY: clean
clean:
	rm -f  match
	rm -f  atof
	rm -f  rev_polish
	rm -f  itoa
	rm -f  reverse
	rm -f  macro_swap
