run_rev_polish: rev_polish.c
	gcc rev_polish.c -o rev_polish

run_atof: e2_atof.c
	gcc e2_atof.c -o atof

run_match: e1_match.c
	gcc e1_match.c -o match

.PHONY: clean
clean:
	rm -f  match
	rm -f  atof
	rm -f  rev_polish
