run_strn: e5_strn.c
	gcc e5_strn.c -o strn

run_strend: e4_strend.c
	gcc e4_strend.c -o strend

run_strcat: e3_strcat.c
	gcc e3_strcat.c -o strcat

run_getfloat: e2_getfloat.c
	gcc e2_getfloat.c -o getfloat

run_getint: e1_getint.c
	gcc e1_getint.c -o getint

.PHONY: clean
clean:
	rm -f getint
	rm -f getfloat
	rm -f strcat
	rm -f strend
	rm -f strn
