run_tail: e13_tail.c
	gcc e13_tail.c -o tail

run_rev_polish_cmd: e10_rev_polish_cmd.c
	gcc e10_rev_polish_cmd.c -o expr

run_y2k: e9_conv_years.c
	gcc e9_conv_years.c -o y2k

run_strn: e5_strn.c
	gcc e5_strn.c -o strn

run_strend: e4_strend.c
	gcc e4_strend.c -o strend

run_strcat: e3_strcat.c
	gcc e3_strcat.c -o strcat

run_getfloat: e2_getfloat.c
	gcc e2_getfloat.c -o getfloat

run_getint: e1_getint.c
	gcc e1_getint.c -o getint

.PHONY: clean
clean:
	rm -f getint
	rm -f getfloat
	rm -f strcat
	rm -f strend
	rm -f strn
	rm -f y2k
	rm -f expr
	rm -f tail

