run_fold: e22_fold.c
	gcc e22_fold.c -o fold

run_entab: e21_entab.c
	gcc e21_entab.c -o entab

run_detab: e20_detab.c
	gcc e20_detab.c -o detab

run_rev_longest_line_len: e19_rev_longest_line_len.c
	gcc e19_rev_longest_line_len.c -o rev_longest_line_len

run_clean_longest_line: e18_clean_longest_line.c
	gcc e18_clean_longest_line.c -o clean_longest_line

run_longer_than80: e17_longer_than80.c
	gcc e17_longer_than80.c -o longer_than80

run_longest_line_len: e16_longest_line_len.c
	gcc e16_longest_line_len.c -o longest_line_len

run_temp_func: e15_temp_func.c
	gcc e15_temp_func.c -o temp_func

run_hist_char_freq: e14_hist_char_freq.c
	gcc e14_hist_char_freq.c -o hist_char_freq

run_hist_word_len: e13_histo_word_len.c
	gcc e13_histo_word_len.c -o hist_word_len

run_special_copy3: e12_special_copy3.c
	gcc e12_special_copy3.c -o special_copy3

run_special_copy2: e10_special_copy2.c
	gcc e10_special_copy2.c -o special_copy2

run_special_copy: e9_special_copy.c
	gcc e9_special_copy.c -o special_copy

run_count_line_feats: e8_count_line_feats.c
	gcc e8_count_line_feats.c -o line_feats

run_print_eof: e7_print_eof.c
	gcc e7_print_eof.c -o print_eof

run_verify_eof: e6_verify_eof.c
	gcc e6_verify_eof.c -o verify_eof

run_rev_fahr2cels: e5_rev_fahr2cels.c
	gcc e5_rev_fahr2cels.c -o rev_fahr2cels

run_cels2fahr: e4_cels2fahr.c
	nt fahr;gcc e4_cels2fahr.c -o cels2fahr

run_fahr2cels: e3_temp_heading.c
	gcc e3_temp_heading.c -o fahr2cels

run_printf_special: e2_printf_special.c
	gcc e2_printf_special.c -o special

run_hello: e1_hello_world.c
	gcc e1_hello_world.c -o hello

.PHONY: clean
clean:
	rm -f hello
	rm -f special
	rm -f fahr2cels
	rm -f cels2fahr
	rm -f rev_fahr2cels
	rm -f verify_eof
	rm -f print_eof
	rm -f line_feats
	rm -f special_copy
	rm -f special_copy2
	rm -f special_copy3
	rm -f hist_word_len
	rm -f hist_char_freq
	rm -f temp_func
	rm -f longest_line_len
	rm -f longer_than80
	rm -f clean_longest_line
	rm -f rev_longest_line_len
	rm -f detab
	rm -f entab
	rm -f fold

